/**
 * element-data.js —— 元素周期表数据表（纯数据，无逻辑）
 * 四张表均以元素符号 sym 为键，与 118 个元素一一对应，由文件末尾的启动自检保证：
 *   ELEMENTS      基础信息：符号 / 英文名 / 中文名 / 拼音 / 相对原子质量 / 族 / 表格行
 *   ELEMENT_EXTRAS 分类 / 常温状态 / 一句话简介（分类决定卡片底色，见 main.js 的 CAT_COLORS）
 *   ELEMENT_MORE  发现（年代 / 发现者 / 方式）与主要用途
 *   ELEMENT_PHYS  物理性质：熔点 / 沸点 / 密度
 */

  /* ---------------- 元素数据 ---------------- */
  // 118 个元素（符号 / 英文名 / 中文名 / 拼音（自带声调符号） / 相对原子质量 / 族 / 表格行）；
  // 质量值带括号表示无稳定同位素元素的半衰期最长同位素质量。
  // 行布局：主表用 period 1~7；镧系占第 9 行、锕系占第 10 行（独立排在主表下方，中间空一行）
  var ELEMENTS = [
    { sym: "H", name: "Hydrogen", zh: "氢", pinyin: "qīng", mass: "1.00794", group: 1, period: 1 },
    { sym: "He", name: "Helium", zh: "氦", pinyin: "hài", mass: "4.002602", group: 18, period: 1 },
    { sym: "Li", name: "Lithium", zh: "锂", pinyin: "lǐ", mass: "6.941", group: 1, period: 2 },
    { sym: "Be", name: "Beryllium", zh: "铍", pinyin: "pí", mass: "9.012182", group: 2, period: 2 },
    { sym: "B", name: "Boron", zh: "硼", pinyin: "péng", mass: "10.811", group: 13, period: 2 },
    { sym: "C", name: "Carbon", zh: "碳", pinyin: "tàn", mass: "12.0107", group: 14, period: 2 },
    { sym: "N", name: "Nitrogen", zh: "氮", pinyin: "dàn", mass: "14.0067", group: 15, period: 2 },
    { sym: "O", name: "Oxygen", zh: "氧", pinyin: "yǎng", mass: "15.9994", group: 16, period: 2 },
    { sym: "F", name: "Fluorine", zh: "氟", pinyin: "fú", mass: "18.9984032", group: 17, period: 2 },
    { sym: "Ne", name: "Neon", zh: "氖", pinyin: "nǎi", mass: "20.1797", group: 18, period: 2 },
    { sym: "Na", name: "Sodium", zh: "钠", pinyin: "nà", mass: "22.98977", group: 1, period: 3 },
    { sym: "Mg", name: "Magnesium", zh: "镁", pinyin: "měi", mass: "24.305", group: 2, period: 3 },
    { sym: "Al", name: "Aluminium", zh: "铝", pinyin: "lǚ", mass: "26.9815386", group: 13, period: 3 },
    { sym: "Si", name: "Silicon", zh: "硅", pinyin: "guī", mass: "28.0855", group: 14, period: 3 },
    { sym: "P", name: "Phosphorus", zh: "磷", pinyin: "lín", mass: "30.973762", group: 15, period: 3 },
    { sym: "S", name: "Sulfur", zh: "硫", pinyin: "liú", mass: "32.065", group: 16, period: 3 },
    { sym: "Cl", name: "Chlorine", zh: "氯", pinyin: "lǜ", mass: "35.453", group: 17, period: 3 },
    { sym: "Ar", name: "Argon", zh: "氩", pinyin: "yà", mass: "39.948", group: 18, period: 3 },
    { sym: "K", name: "Potassium", zh: "钾", pinyin: "jiǎ", mass: "39.0983", group: 1, period: 4 },
    { sym: "Ca", name: "Calcium", zh: "钙", pinyin: "gài", mass: "40.078", group: 2, period: 4 },
    { sym: "Sc", name: "Scandium", zh: "钪", pinyin: "kàng", mass: "44.955912", group: 3, period: 4 },
    { sym: "Ti", name: "Titanium", zh: "钛", pinyin: "tài", mass: "47.867", group: 4, period: 4 },
    { sym: "V", name: "Vanadium", zh: "钒", pinyin: "fán", mass: "50.9415", group: 5, period: 4 },
    { sym: "Cr", name: "Chromium", zh: "铬", pinyin: "gè", mass: "51.9961", group: 6, period: 4 },
    { sym: "Mn", name: "Manganese", zh: "锰", pinyin: "měng", mass: "54.938045", group: 7, period: 4 },
    { sym: "Fe", name: "Iron", zh: "铁", pinyin: "tiě", mass: "55.845", group: 8, period: 4 },
    { sym: "Co", name: "Cobalt", zh: "钴", pinyin: "gǔ", mass: "58.933195", group: 9, period: 4 },
    { sym: "Ni", name: "Nickel", zh: "镍", pinyin: "niè", mass: "58.6934", group: 10, period: 4 },
    { sym: "Cu", name: "Copper", zh: "铜", pinyin: "tóng", mass: "63.546", group: 11, period: 4 },
    { sym: "Zn", name: "Zinc", zh: "锌", pinyin: "xīn", mass: "65.38", group: 12, period: 4 },
    { sym: "Ga", name: "Gallium", zh: "镓", pinyin: "jiā", mass: "69.723", group: 13, period: 4 },
    { sym: "Ge", name: "Germanium", zh: "锗", pinyin: "zhě", mass: "72.63", group: 14, period: 4 },
    { sym: "As", name: "Arsenic", zh: "砷", pinyin: "shēn", mass: "74.9216", group: 15, period: 4 },
    { sym: "Se", name: "Selenium", zh: "硒", pinyin: "xī", mass: "78.96", group: 16, period: 4 },
    { sym: "Br", name: "Bromine", zh: "溴", pinyin: "xiù", mass: "79.904", group: 17, period: 4 },
    { sym: "Kr", name: "Krypton", zh: "氪", pinyin: "kè", mass: "83.798", group: 18, period: 4 },
    { sym: "Rb", name: "Rubidium", zh: "铷", pinyin: "rú", mass: "85.4678", group: 1, period: 5 },
    { sym: "Sr", name: "Strontium", zh: "锶", pinyin: "sī", mass: "87.62", group: 2, period: 5 },
    { sym: "Y", name: "Yttrium", zh: "钇", pinyin: "yǐ", mass: "88.90585", group: 3, period: 5 },
    { sym: "Zr", name: "Zirconium", zh: "锆", pinyin: "gào", mass: "91.224", group: 4, period: 5 },
    { sym: "Nb", name: "Niobium", zh: "铌", pinyin: "ní", mass: "92.90628", group: 5, period: 5 },
    { sym: "Mo", name: "Molybdenum", zh: "钼", pinyin: "mù", mass: "95.96", group: 6, period: 5 },
    { sym: "Tc", name: "Technetium", zh: "锝", pinyin: "dé", mass: "(98)", group: 7, period: 5 },
    { sym: "Ru", name: "Ruthenium", zh: "钌", pinyin: "liǎo", mass: "101.07", group: 8, period: 5 },
    { sym: "Rh", name: "Rhodium", zh: "铑", pinyin: "lǎo", mass: "102.9055", group: 9, period: 5 },
    { sym: "Pd", name: "Palladium", zh: "钯", pinyin: "bǎ", mass: "106.42", group: 10, period: 5 },
    { sym: "Ag", name: "Silver", zh: "银", pinyin: "yín", mass: "107.8682", group: 11, period: 5 },
    { sym: "Cd", name: "Cadmium", zh: "镉", pinyin: "gé", mass: "112.411", group: 12, period: 5 },
    { sym: "In", name: "Indium", zh: "铟", pinyin: "yīn", mass: "114.818", group: 13, period: 5 },
    { sym: "Sn", name: "Tin", zh: "锡", pinyin: "xī", mass: "118.71", group: 14, period: 5 },
    { sym: "Sb", name: "Antimony", zh: "锑", pinyin: "tī", mass: "121.76", group: 15, period: 5 },
    { sym: "Te", name: "Tellurium", zh: "碲", pinyin: "dì", mass: "127.6", group: 16, period: 5 },
    { sym: "I", name: "Iodine", zh: "碘", pinyin: "diǎn", mass: "126.90447", group: 17, period: 5 },
    { sym: "Xe", name: "Xenon", zh: "氙", pinyin: "xiān", mass: "131.293", group: 18, period: 5 },
    { sym: "Cs", name: "Caesium", zh: "铯", pinyin: "sè", mass: "132.9054", group: 1, period: 6 },
    { sym: "Ba", name: "Barium", zh: "钡", pinyin: "bèi", mass: "137.327", group: 2, period: 6 },
    { sym: "La", name: "Lanthanum", zh: "镧", pinyin: "lán", mass: "138.90547", group: 4, period: 9 },
    { sym: "Ce", name: "Cerium", zh: "铈", pinyin: "shì", mass: "140.116", group: 5, period: 9 },
    { sym: "Pr", name: "Praseodymium", zh: "镨", pinyin: "pǔ", mass: "140.90765", group: 6, period: 9 },
    { sym: "Nd", name: "Neodymium", zh: "钕", pinyin: "nǚ", mass: "144.242", group: 7, period: 9 },
    { sym: "Pm", name: "Promethium", zh: "钷", pinyin: "pǒ", mass: "(145)", group: 8, period: 9 },
    { sym: "Sm", name: "Samarium", zh: "钐", pinyin: "shān", mass: "150.36", group: 9, period: 9 },
    { sym: "Eu", name: "Europium", zh: "铕", pinyin: "yǒu", mass: "151.964", group: 10, period: 9 },
    { sym: "Gd", name: "Gadolinium", zh: "钆", pinyin: "gá", mass: "157.25", group: 11, period: 9 },
    { sym: "Tb", name: "Terbium", zh: "铽", pinyin: "tè", mass: "158.92535", group: 12, period: 9 },
    { sym: "Dy", name: "Dysprosium", zh: "镝", pinyin: "dī", mass: "162.5", group: 13, period: 9 },
    { sym: "Ho", name: "Holmium", zh: "钬", pinyin: "huǒ", mass: "164.93032", group: 14, period: 9 },
    { sym: "Er", name: "Erbium", zh: "铒", pinyin: "ěr", mass: "167.259", group: 15, period: 9 },
    { sym: "Tm", name: "Thulium", zh: "铥", pinyin: "diū", mass: "168.93421", group: 16, period: 9 },
    { sym: "Yb", name: "Ytterbium", zh: "镱", pinyin: "yì", mass: "173.054", group: 17, period: 9 },
    { sym: "Lu", name: "Lutetium", zh: "镥", pinyin: "lǔ", mass: "174.9668", group: 18, period: 9 },
    { sym: "Hf", name: "Hafnium", zh: "铪", pinyin: "hā", mass: "178.49", group: 4, period: 6 },
    { sym: "Ta", name: "Tantalum", zh: "钽", pinyin: "tǎn", mass: "180.94788", group: 5, period: 6 },
    { sym: "W", name: "Tungsten", zh: "钨", pinyin: "wū", mass: "183.84", group: 6, period: 6 },
    { sym: "Re", name: "Rhenium", zh: "铼", pinyin: "lái", mass: "186.207", group: 7, period: 6 },
    { sym: "Os", name: "Osmium", zh: "锇", pinyin: "é", mass: "190.23", group: 8, period: 6 },
    { sym: "Ir", name: "Iridium", zh: "铱", pinyin: "yī", mass: "192.217", group: 9, period: 6 },
    { sym: "Pt", name: "Platinum", zh: "铂", pinyin: "bó", mass: "195.084", group: 10, period: 6 },
    { sym: "Au", name: "Gold", zh: "金", pinyin: "jīn", mass: "196.966569", group: 11, period: 6 },
    { sym: "Hg", name: "Mercury", zh: "汞", pinyin: "gǒng", mass: "200.59", group: 12, period: 6 },
    { sym: "Tl", name: "Thallium", zh: "铊", pinyin: "tā", mass: "204.3833", group: 13, period: 6 },
    { sym: "Pb", name: "Lead", zh: "铅", pinyin: "qiān", mass: "207.2", group: 14, period: 6 },
    { sym: "Bi", name: "Bismuth", zh: "铋", pinyin: "bì", mass: "208.9804", group: 15, period: 6 },
    { sym: "Po", name: "Polonium", zh: "钋", pinyin: "pō", mass: "(209)", group: 16, period: 6 },
    { sym: "At", name: "Astatine", zh: "砹", pinyin: "ài", mass: "(210)", group: 17, period: 6 },
    { sym: "Rn", name: "Radon", zh: "氡", pinyin: "dōng", mass: "(222)", group: 18, period: 6 },
    { sym: "Fr", name: "Francium", zh: "钫", pinyin: "fāng", mass: "(223)", group: 1, period: 7 },
    { sym: "Ra", name: "Radium", zh: "镭", pinyin: "léi", mass: "(226)", group: 2, period: 7 },
    { sym: "Ac", name: "Actinium", zh: "锕", pinyin: "ā", mass: "(227)", group: 4, period: 10 },
    { sym: "Th", name: "Thorium", zh: "钍", pinyin: "tǔ", mass: "232.03806", group: 5, period: 10 },
    { sym: "Pa", name: "Protactinium", zh: "镤", pinyin: "pú", mass: "231.0588", group: 6, period: 10 },
    { sym: "U", name: "Uranium", zh: "铀", pinyin: "yóu", mass: "238.02891", group: 7, period: 10 },
    { sym: "Np", name: "Neptunium", zh: "镎", pinyin: "ná", mass: "(237)", group: 8, period: 10 },
    { sym: "Pu", name: "Plutonium", zh: "钚", pinyin: "bù", mass: "(244)", group: 9, period: 10 },
    { sym: "Am", name: "Americium", zh: "镅", pinyin: "méi", mass: "(243)", group: 10, period: 10 },
    { sym: "Cm", name: "Curium", zh: "锔", pinyin: "jú", mass: "(247)", group: 11, period: 10 },
    { sym: "Bk", name: "Berkelium", zh: "锫", pinyin: "péi", mass: "(247)", group: 12, period: 10 },
    { sym: "Cf", name: "Californium", zh: "锎", pinyin: "kāi", mass: "(251)", group: 13, period: 10 },
    { sym: "Es", name: "Einsteinium", zh: "锿", pinyin: "āi", mass: "(252)", group: 14, period: 10 },
    { sym: "Fm", name: "Fermium", zh: "镄", pinyin: "fèi", mass: "(257)", group: 15, period: 10 },
    { sym: "Md", name: "Mendelevium", zh: "钔", pinyin: "mén", mass: "(258)", group: 16, period: 10 },
    { sym: "No", name: "Nobelium", zh: "锘", pinyin: "nuò", mass: "(259)", group: 17, period: 10 },
    { sym: "Lr", name: "Lawrencium", zh: "铹", pinyin: "láo", mass: "(266)", group: 18, period: 10 },
    { sym: "Rf", name: "Rutherfordium", zh: "𬬻", pinyin: "lú", mass: "(267)", group: 4, period: 7 },
    { sym: "Db", name: "Dubnium", zh: "𬭊", pinyin: "láo", mass: "(268)", group: 5, period: 7 },
    { sym: "Sg", name: "Seaborgium", zh: "𬭳", pinyin: "xī", mass: "(269)", group: 6, period: 7 },
    { sym: "Bh", name: "Bohrium", zh: "𬭛", pinyin: "bō", mass: "(270)", group: 7, period: 7 },
    { sym: "Hs", name: "Hassium", zh: "𬭶", pinyin: "hēi", mass: "(269)", group: 8, period: 7 },
    { sym: "Mt", name: "Meitnerium", zh: "鿏", pinyin: "mài", mass: "(278)", group: 9, period: 7 },
    { sym: "Ds", name: "Darmstadtium", zh: "𬭸", pinyin: "lún", mass: "(281)", group: 10, period: 7 },
    { sym: "Rg", name: "Roentgenium", zh: "𬬬", pinyin: "lǎi", mass: "(282)", group: 11, period: 7 },
    { sym: "Cn", name: "Copernicium", zh: "鿔", pinyin: "gē", mass: "(285)", group: 12, period: 7 },
    { sym: "Nh", name: "Nihonium", zh: "鿭", pinyin: "nǐ", mass: "(286)", group: 13, period: 7 },
    { sym: "Fl", name: "Flerovium", zh: "𫓧", pinyin: "fú", mass: "(289)", group: 14, period: 7 },
    { sym: "Mc", name: "Moscovium", zh: "镆", pinyin: "mò", mass: "(289)", group: 15, period: 7 },
    { sym: "Lv", name: "Livermorium", zh: "𫟅", pinyin: "lì", mass: "(293)", group: 16, period: 7 },
    { sym: "Ts", name: "Tennessine", zh: "鿬", pinyin: "tián", mass: "(294)", group: 17, period: 7 },
    { sym: "Og", name: "Oganesson", zh: "鿫", pinyin: "ào", mass: "(294)", group: 18, period: 7 },
  ];

  /* ---------------- 元素扩展信息（按符号 sym 一一对应，勿靠行序对齐） ---------------- */
  // cat：元素分类（决定卡片底色）；state：常温状态（固 / 液 / 气 / 放射性）；desc：一句话简介。
  // 分类底色见 CAT_COLORS；放射性元素（Tc / Pm / Po ~ Og）state 为"放射性"，卡片带红色角标 + 红色虚线描边。
  // 注意：锕系元素（Ac ~ Lr）归入"锕系元素"分类（深紫色底），同时带放射性标记。
  var ELEMENT_EXTRAS = {
    "H": { cat: "非金属", state: "气", desc: "宇宙中丰度最高的元素，水的组成成分。" },
    "He": { cat: "稀有气体", state: "气", desc: "最轻的稀有气体，用于填充飞艇与低温冷却。" },
    "Li": { cat: "碱金属", state: "固", desc: "最轻的金属，锂电池的核心材料。" },
    "Be": { cat: "碱土金属", state: "固", desc: "轻而坚硬的金属，铍铜合金用于航天器材。" },
    "B": { cat: "类金属", state: "固", desc: "硼砂与硼酸的主要元素，玻璃与洗涤剂原料。" },
    "C": { cat: "非金属", state: "固", desc: "生命骨架元素，存在于一切有机物中。" },
    "N": { cat: "非金属", state: "气", desc: "占大气 78%，是蛋白质与氨基酸的组成元素。" },
    "O": { cat: "非金属", state: "气", desc: "生命必需元素，呼吸作用与燃烧都离不开它。" },
    "F": { cat: "卤素", state: "气", desc: "最活泼的非金属，牙膏中的氟化物可防龋齿。" },
    "Ne": { cat: "稀有气体", state: "气", desc: "通电发出橙红光，霓虹灯的经典发光气体。" },
    "Na": { cat: "碱金属", state: "固", desc: "质地软如蜡，食盐（氯化钠）的主要成分。" },
    "Mg": { cat: "碱土金属", state: "固", desc: "轻质金属，燃烧发出耀眼白光，用于照明弹。" },
    "Al": { cat: "主族金属", state: "固", desc: "轻而耐用，铝箔、易拉罐与航空航天材料。" },
    "Si": { cat: "类金属", state: "固", desc: "芯片与光纤的核心材料，信息时代的基石。" },
    "P": { cat: "非金属", state: "固", desc: "磷肥与 DNA 的组成元素，白磷在空气中自燃。" },
    "S": { cat: "非金属", state: "固", desc: "橡胶硫化的关键元素，也是硫酸的原料。" },
    "Cl": { cat: "卤素", state: "气", desc: "黄绿色有毒气体，用于自来水消毒。" },
    "Ar": { cat: "稀有气体", state: "气", desc: "极不活泼，用于保护焊接与白炽灯填充。" },
    "K": { cat: "碱金属", state: "固", desc: "密度比水还小，燃烧发出紫色火焰。" },
    "Ca": { cat: "碱土金属", state: "固", desc: "骨骼与牙齿的主要成分，石灰石的主要元素。" },
    "Sc": { cat: "过渡金属", state: "固", desc: "轻质耐热金属，用于自行车架与人工关节。" },
    "Ti": { cat: "过渡金属", state: "固", desc: "强度高且耐腐蚀，钛合金广泛用于航空领域。" },
    "V": { cat: "过渡金属", state: "固", desc: "硬度极高，钒钢用于工具与弹簧制造。" },
    "Cr": { cat: "过渡金属", state: "固", desc: "不锈钢的必需成分，化合物呈现斑斓色彩。" },
    "Mn": { cat: "过渡金属", state: "固", desc: "地壳中丰度较高的过渡金属，高锰酸钾呈紫色。" },
    "Fe": { cat: "过渡金属", state: "固", desc: "地壳中最丰富的金属，血红蛋白的核心元素。" },
    "Co": { cat: "过渡金属", state: "固", desc: "蓝色玻璃的呈色元素，维生素 B12 的核心金属。" },
    "Ni": { cat: "过渡金属", state: "固", desc: "耐腐蚀，古代中国的白铜即含镍。" },
    "Cu": { cat: "过渡金属", state: "固", desc: "优良导体，电线与电路的主要材料。" },
    "Zn": { cat: "过渡金属", state: "固", desc: "人体必需微量元素，镀锌钢板防锈的关键。" },
    "Ga": { cat: "主族金属", state: "固", desc: "熔点极低的软金属，砷化镓用于半导体。" },
    "Ge": { cat: "类金属", state: "固", desc: "与二氧化硅同源的元素，高纯锗用于红外光学。" },
    "As": { cat: "类金属", state: "固", desc: "有剧毒的类金属，古代砒霜的主要成分。" },
    "Se": { cat: "非金属", state: "固", desc: "导电性随光照变化，硒鼓复印机的核心。" },
    "Br": { cat: "卤素", state: "液", desc: "常温下唯一的液态非金属，用于阻燃剂。" },
    "Kr": { cat: "稀有气体", state: "气", desc: "通电发出明亮白光，曾用于高速摄影闪光灯。" },
    "Rb": { cat: "碱金属", state: "固", desc: "极活泼的碱金属，铷原子钟用于卫星导航。" },
    "Sr": { cat: "碱土金属", state: "固", desc: "燃烧发出鲜红色火焰，用于烟花与信号弹。" },
    "Y": { cat: "过渡金属", state: "固", desc: "钇铝石榴石用于激光器，高温超导研究材料。" },
    "Zr": { cat: "过渡金属", state: "固", desc: "耐腐蚀的银白金属，锆合金用于核燃料包壳。" },
    "Nb": { cat: "过渡金属", state: "固", desc: "超导材料的著名成分，铌钛合金用于核磁共振。" },
    "Mo": { cat: "过渡金属", state: "固", desc: "熔点极高的金属，钼丝可用于高温电炉。" },
    "Tc": { cat: "放射性", state: "放射性", desc: "首个由人工合成的元素，用于医学示踪。" },
    "Ru": { cat: "过渡金属", state: "固", desc: "耐腐蚀的铂族金属，铱钌合金用于钢笔尖。" },
    "Rh": { cat: "过渡金属", state: "固", desc: "反射率极高的铂族金属，用于车灯镀层。" },
    "Pd": { cat: "过渡金属", state: "固", desc: "钯金可用于催化汽车尾气净化。" },
    "Ag": { cat: "过渡金属", state: "固", desc: "导电性最佳的金属，胶片感光材料的核心。" },
    "Cd": { cat: "过渡金属", state: "固", desc: "镉黄颜料与镍镉电池的成分，毒性较强。" },
    "In": { cat: "主族金属", state: "固", desc: "铟锡氧化物是触摸屏透明电极的材料。" },
    "Sn": { cat: "主族金属", state: "固", desc: "青铜的主要成分，锡焊料广泛用于电子工业。" },
    "Sb": { cat: "类金属", state: "固", desc: "锑化物用于阻燃剂，古代用作化妆品原料。" },
    "Te": { cat: "类金属", state: "固", desc: "玻璃制造的关键添加剂，碲化镉用于太阳能电池。" },
    "I": { cat: "卤素", state: "固", desc: "紫黑色固体，升华成紫色蒸气，碘酒可消毒。" },
    "Xe": { cat: "稀有气体", state: "气", desc: "氙灯亮度极高，也用作麻醉剂。" },
    "Cs": { cat: "碱金属", state: "固", desc: "熔点仅 28 度，空气中自燃，最活泼的金属之一。" },
    "Ba": { cat: "碱土金属", state: "固", desc: "硫酸钡可用于胃肠 X 光造影。" },
    "La": { cat: "镧系元素", state: "固", desc: "镧系之首，混合镧系金属用于打火石。" },
    "Ce": { cat: "镧系元素", state: "固", desc: "打火石与特种玻璃的成分，氧化铈可抛光玻璃。" },
    "Pr": { cat: "镧系元素", state: "固", desc: "磁性与光学性能独特，用于特种有色玻璃。" },
    "Nd": { cat: "镧系元素", state: "固", desc: "钕铁硼是最强永磁体，广泛用于电机与硬盘。" },
    "Pm": { cat: "放射性", state: "放射性", desc: "镧系中唯一放射性元素，用于核电池与示踪研究。" },
    "Sm": { cat: "镧系元素", state: "固", desc: "激光器的关键元素，钐钴磁体耐高温。" },
    "Eu": { cat: "镧系元素", state: "固", desc: "红色荧光粉与节能灯的成分。" },
    "Gd": { cat: "镧系元素", state: "固", desc: "磁制冷与核反应堆控制棒材料。" },
    "Tb": { cat: "镧系元素", state: "固", desc: "绿色荧光粉的激活剂，铽铁磁致伸缩材料。" },
    "Dy": { cat: "镧系元素", state: "固", desc: "镝灯亮度高，用于电影放映与舞台照明。" },
    "Ho": { cat: "镧系元素", state: "固", desc: "镧系磁矩最大元素，用于磁光存储。" },
    "Er": { cat: "镧系元素", state: "固", desc: "激光常用元素，铒光纤放大器支撑光纤通信。" },
    "Tm": { cat: "镧系元素", state: "固", desc: "唯一的奇核稳定同位素元素，用于 X 射线管。" },
    "Yb": { cat: "镧系元素", state: "固", desc: "镱原子钟是目前最精准的时钟之一。" },
    "Lu": { cat: "镧系元素", state: "固", desc: "镥铝酸盐闪烁体用于医学成像。" },
    "Hf": { cat: "过渡金属", state: "固", desc: "铪锆比用于核工业，控制棒的重要材料。" },
    "Ta": { cat: "过渡金属", state: "固", desc: "电容器的重要材料，碳化钽极硬且耐磨。" },
    "W": { cat: "过渡金属", state: "固", desc: "熔点最高的金属，白炽灯丝曾是它的天下。" },
    "Re": { cat: "过渡金属", state: "固", desc: "铼是熔点第二高的金属，用于航空发动机叶片。" },
    "Os": { cat: "过渡金属", state: "固", desc: "密度最大的金属，锇铱合金用于笔尖。" },
    "Ir": { cat: "过渡金属", state: "固", desc: "化学性质极稳定的铂族金属，国际千克原器为铂铱合金。" },
    "Pt": { cat: "过渡金属", state: "固", desc: "化学性质稳定，首饰与催化工业的核心材料。" },
    "Au": { cat: "过渡金属", state: "固", desc: "延展性最好的金属，首饰与电子工业的宠儿。" },
    "Hg": { cat: "过渡金属", state: "液", desc: "常温下唯一的液态金属，温度计与荧光灯曾用它。" },
    "Tl": { cat: "主族金属", state: "固", desc: "铊盐剧毒，曾用于灭鼠，现用于红外探测。" },
    "Pb": { cat: "主族金属", state: "固", desc: "铅酸电池的主要材料，密度大且柔软。" },
    "Bi": { cat: "主族金属", state: "固", desc: "铋晶体呈现彩虹色泽，用于胃药与低熔点合金。" },
    "Po": { cat: "放射性", state: "放射性", desc: "放射性金属，钋毒性强，曾引发历史悬案。" },
    "At": { cat: "放射性", state: "放射性", desc: "天然元素中最稀有的之一，至今无实用价值。" },
    "Rn": { cat: "放射性", state: "放射性", desc: "天然放射性稀有气体，地下室需防范氡气。" },
    "Fr": { cat: "放射性", state: "放射性", desc: "碱金属中最稀有元素，半衰期极短，天然含量几乎为零。" },
    "Ra": { cat: "放射性", state: "放射性", desc: "镭的放射性由居里夫妇发现，曾用于夜光涂料。" },
    "Ac": { cat: "锕系元素", state: "放射性", desc: "锕系之首，天然存在于铀矿中。" },
    "Th": { cat: "锕系元素", state: "放射性", desc: "钍基核电研究的燃料，氧化钍曾用于汽灯纱罩。" },
    "Pa": { cat: "锕系元素", state: "放射性", desc: "首个锕系元素，镤的发现历经十余年。" },
    "U": { cat: "锕系元素", state: "放射性", desc: "核燃料与核武器的核心元素，铀浓缩备受关注。" },
    "Np": { cat: "锕系元素", state: "放射性", desc: "首个完全人工合成的锕系元素。" },
    "Pu": { cat: "锕系元素", state: "放射性", desc: "核武器与核电池的常用材料。" },
    "Am": { cat: "锕系元素", state: "放射性", desc: "烟雾探测器中的镅-241 电离室。" },
    "Cm": { cat: "锕系元素", state: "放射性", desc: "主要用于科学研究，人工合成产量极低。" },
    "Bk": { cat: "锕系元素", state: "放射性", desc: "以加州伯克利命名的元素。" },
    "Cf": { cat: "锕系元素", state: "放射性", desc: "以加州命名的元素，锎-252 是强中子源。" },
    "Es": { cat: "锕系元素", state: "放射性", desc: "以爱因斯坦命名，产量以原子数计。" },
    "Fm": { cat: "锕系元素", state: "放射性", desc: "以费米命名，仅能在实验室微量合成。" },
    "Md": { cat: "锕系元素", state: "放射性", desc: "以门捷列夫命名，人工合成元素之一。" },
    "No": { cat: "锕系元素", state: "放射性", desc: "以诺贝尔命名，半衰期较短。" },
    "Lr": { cat: "锕系元素", state: "放射性", desc: "以回旋加速器发明者劳伦斯命名。" },
    "Rf": { cat: "放射性", state: "放射性", desc: "以卢瑟福命名，首个超铀元素。" },
    "Db": { cat: "放射性", state: "放射性", desc: "以杜布纳联合核子研究所命名。" },
    "Sg": { cat: "放射性", state: "放射性", desc: "以西博格命名，这是首个以在世人物命名的元素。" },
    "Bh": { cat: "放射性", state: "放射性", desc: "以玻尔命名，半衰期极短。" },
    "Hs": { cat: "放射性", state: "放射性", desc: "以黑森州命名，人工合成量以原子数计。" },
    "Mt": { cat: "放射性", state: "放射性", desc: "以迈特纳命名，与 LISA 探测器研究相关。" },
    "Ds": { cat: "放射性", state: "放射性", desc: "以达姆施塔特命名，半衰期仅数秒。" },
    "Rg": { cat: "放射性", state: "放射性", desc: "以伦琴命名，X 射线发现者的荣誉。" },
    "Cn": { cat: "放射性", state: "放射性", desc: "以哥白尼命名，性质与汞相似。" },
    "Nh": { cat: "放射性", state: "放射性", desc: "以日本理化学研究所命名，首个亚洲命名的元素。" },
    "Fl": { cat: "放射性", state: "放射性", desc: "以俄罗斯杜布纳附近的莫斯科州命名。" },
    "Mc": { cat: "放射性", state: "放射性", desc: "以弗廖罗夫命名，可能是一种类金属。" },
    "Lv": { cat: "放射性", state: "放射性", desc: "以劳伦斯利弗莫尔实验室命名。" },
    "Ts": { cat: "放射性", state: "放射性", desc: "以田纳西州命名，卤素家族最重的成员。" },
    "Og": { cat: "放射性", state: "放射性", desc: "第 118 号元素，以奥加尼扬命名，仅合成数个原子。" },
  };

  /* 元素扩展信息第二表：发现（年代 / 发现者 / 方式）与主要用途，按 sym 与 ELEMENTS 一一对应（同受启动自检约束） */
  var ELEMENT_MORE = {
    "H": { disc: "1766 年由英国化学家卡文迪什发现。", use: "合成氨、石油精炼、氢燃料电池与火箭推进剂。" },
    "He": { disc: "1868 年在太阳光谱中发现，1895 年由拉姆塞在地球上分离。", use: "飞艇填充、深海呼吸混合气、磁共振超导磁体冷却。" },
    "Li": { disc: "1817 年由阿尔费特森发现。", use: "锂电池、轻质合金、玻璃陶瓷，碳酸锂用作情绪稳定剂。" },
    "Be": { disc: "1798 年由沃克兰发现。", use: "铍铜合金弹簧接点、X 射线管窗口、航天结构件。" },
    "B": { disc: "1808 年由戴维与盖-吕萨克分别制得。", use: "硼硅玻璃、硼砂洗涤剂、半导体掺杂剂。" },
    "C": { disc: "远古即知，木炭与煤自古使用。", use: "钢铁冶炼、金刚石刀具、石墨电极、碳纤维材料。" },
    "N": { disc: "1772 年由丹尼尔·卢瑟福发现。", use: "合成氨与化肥、液氮冷冻、食品包装保护气。" },
    "O": { disc: "1774 年由普里斯特利与舍勒发现。", use: "炼钢助燃、医疗供氧、火箭氧化剂。" },
    "F": { disc: "1886 年由莫瓦桑电解制得。", use: "含氟牙膏、特氟龙不粘涂层、铀浓缩原料六氟化铀。" },
    "Ne": { disc: "1898 年由拉姆塞与特拉弗斯发现。", use: "霓虹灯、氦氖激光器、低温制冷剂。" },
    "Na": { disc: "1807 年由戴维电解制得。", use: "钠灯、烧碱与纯碱工业、钠冷快堆冷却剂。" },
    "Mg": { disc: "1808 年由戴维首次分离。", use: "轻质镁合金、格氏试剂、照明弹与焰火。" },
    "Al": { disc: "1825 年由奥斯特发现。", use: "铝箔与易拉罐、航空结构、高压电缆。" },
    "Si": { disc: "1824 年由贝采利乌斯制得。", use: "芯片与太阳能电池、玻璃、有机硅密封材料。" },
    "P": { disc: "1669 年由布兰德蒸馏尿液发现。", use: "磷肥、火柴、磷酸盐食品添加剂。" },
    "S": { disc: "远古即知，古代称\"硫石\"。", use: "硫酸制造、橡胶硫化、火药与杀菌剂。" },
    "Cl": { disc: "1774 年由舍勒制得。", use: "自来水消毒、PVC 塑料、漂白剂。" },
    "Ar": { disc: "1894 年由瑞利与拉姆塞发现。", use: "焊接保护气、白炽灯填充、氩激光器。" },
    "K": { disc: "1807 年由戴维电解制得。", use: "钾肥、玻璃制造、硝酸钾火药。" },
    "Ca": { disc: "1808 年由戴维首次分离。", use: "水泥与石灰、合金脱氧剂、补钙剂。" },
    "Sc": { disc: "1879 年由尼尔森发现。", use: "铝钪合金（航空与运动器材）、高亮度钪钠灯。" },
    "Ti": { disc: "1791 年由格雷厄尔发现。", use: "航空钛合金、医疗植入物、钛白颜料。" },
    "V": { disc: "1830 年由塞尔夫斯特朗确认发现。", use: "钒钢工具与弹簧、钒液流电池、化工催化剂。" },
    "Cr": { disc: "1797 年由沃克兰发现。", use: "不锈钢、电镀铬层、高温合金。" },
    "Mn": { disc: "1774 年由加恩制得。", use: "炼钢脱氧剂、干电池、高锰酸钾消毒剂。" },
    "Fe": { disc: "远古即知，约公元前 5000 年已使用陨铁。", use: "钢铁（建筑与机械）、血红蛋白、变压器磁芯。" },
    "Co": { disc: "1735 年由布兰特发现。", use: "锂电池正极材料、高温合金、蓝色颜料。" },
    "Ni": { disc: "1751 年由克朗斯泰特发现。", use: "不锈钢、镍氢电池、电镀与硬币。" },
    "Cu": { disc: "约公元前 9000 年已知，古代文明广泛使用。", use: "电线电缆、水管、黄铜与青铜合金。" },
    "Zn": { disc: "古代印度与中国已炼锌，1746 年由马格拉夫分离。", use: "镀锌防锈、黄铜、电池与氧化锌防晒霜。" },
    "Ga": { disc: "1875 年由布瓦博德朗发现。", use: "砷化镓半导体、LED、氮化镓快充电源。" },
    "Ge": { disc: "1886 年由温克勒发现。", use: "红外光学镜头、光纤掺杂、早期晶体管。" },
    "As": { disc: "约 1250 年由马格努斯制得。", use: "合金硬化剂、半导体砷化镓，古代砒霜即砷氧化物。" },
    "Se": { disc: "1817 年由贝采利乌斯发现。", use: "复印机硒鼓、玻璃制造、微量元素补充剂。" },
    "Br": { disc: "1826 年由巴拉尔发现。", use: "阻燃剂、感光乳剂溴化银、钻井液。" },
    "Kr": { disc: "1898 年由拉姆塞与特拉弗斯发现。", use: "高速摄影闪光灯、节能荧光灯、氪激光器。" },
    "Rb": { disc: "1861 年由本生与基尔霍夫光谱发现。", use: "铷原子钟、光电管、特种催化剂。" },
    "Sr": { disc: "1790 年由克劳福德发现。", use: "焰火与信号弹（鲜红色）、铁氧体永磁体。" },
    "Y": { disc: "1794 年由加多林发现。", use: "LED 荧光粉、钇铝石榴石激光器、高温超导材料。" },
    "Zr": { disc: "1789 年由克拉普罗特发现。", use: "核燃料包壳锆合金、人造宝石立方氧化锆、耐酸陶瓷。" },
    "Nb": { disc: "1801 年由哈切特发现。", use: "铌钛超导磁体（核磁共振）、管线钢、铌电容器。" },
    "Mo": { disc: "1778 年由舍勒发现。", use: "高强度合金钢、二硫化钼润滑剂、钼电极。" },
    "Tc": { disc: "1937 年由佩里耶与塞格雷人工合成。", use: "医学影像示踪剂锝-99m（每年数千万次检查）。" },
    "Ru": { disc: "1844 年由克劳斯发现。", use: "钢笔尖铱钌合金、电子触点、化工催化剂。" },
    "Rh": { disc: "1803 年由武拉斯顿发现。", use: "汽车三元催化器、镀铑首饰、玻璃纤维工业。" },
    "Pd": { disc: "1803 年由武拉斯顿发现。", use: "尾气催化净化、多层陶瓷电容、氢气提纯。" },
    "Ag": { disc: "远古即知，古代货币与器皿材料。", use: "导体触点、光伏银浆、感光材料、首饰银器。" },
    "Cd": { disc: "1817 年由施特罗迈尔发现。", use: "镍镉电池、量子点显示材料，镉黄颜料已渐淘汰。" },
    "In": { disc: "1863 年由赖希与里希特光谱发现。", use: "触摸屏 ITO 透明电极、低温焊料、液晶封接。" },
    "Sn": { disc: "远古即知，青铜时代核心金属。", use: "电子焊料、马口铁罐头、青铜合金。" },
    "Sb": { disc: "古代即知，古埃及用作化妆品。", use: "阻燃剂、铅酸电池板栅、半导体掺杂剂。" },
    "Te": { disc: "1782 年由穆勒·冯·赖兴施泰因发现。", use: "碲化镉薄膜太阳能电池、热电制冷材料。" },
    "I": { disc: "1811 年由库尔图瓦发现。", use: "碘酒消毒、加碘盐、CT 造影剂、偏光膜。" },
    "Xe": { disc: "1898 年由拉姆塞与特拉弗斯发现。", use: "氙气大灯、卫星离子推进器、麻醉剂。" },
    "Cs": { disc: "1860 年由本生与基尔霍夫光谱发现。", use: "原子钟（秒的定义基准）、光电倍增管、钻井液。" },
    "Ba": { disc: "1808 年由戴维首次分离。", use: "硫酸钡胃肠造影剂（钡餐）、焰火绿色、重晶石钻井液。" },
    "La": { disc: "1839 年由莫桑德尔发现。", use: "打火石、相机镜头玻璃、储氢合金、石油裂化催化剂。" },
    "Ce": { disc: "1803 年由贝采利乌斯与克拉普罗特发现。", use: "抛光粉、打火石、汽车尾气催化剂、玻璃脱色剂。" },
    "Pr": { disc: "1885 年由冯·韦尔斯巴赫发现。", use: "焊工护目镜、钕铁硼磁体添加剂、特种玻璃着色。" },
    "Nd": { disc: "1885 年由冯·韦尔斯巴赫发现。", use: "钕铁硼永磁体（电机、硬盘、耳机）、钕玻璃激光器。" },
    "Pm": { disc: "1945 年由马林斯基等人人工合成。", use: "核电池、夜光涂料（历史）、厚度测量仪。" },
    "Sm": { disc: "1879 年由布瓦博德朗发现。", use: "钐钴磁体（耐高温）、核反应堆中子吸收棒。" },
    "Eu": { disc: "1901 年由德马克发现。", use: "红色荧光粉、钞票防伪油墨、节能灯三基色荧光体。" },
    "Gd": { disc: "1880 年由德马里尼亚克发现。", use: "核磁共振造影剂、中子吸收材料、磁制冷研究。" },
    "Tb": { disc: "1843 年由莫桑德尔发现。", use: "绿色荧光粉、磁致伸缩材料（声呐）、激光晶体。" },
    "Dy": { disc: "1886 年由布瓦博德朗发现。", use: "钕磁体耐高温添加剂、镝灯（电影放映）、核控制棒。" },
    "Ho": { disc: "1878 年由索雷特与克莱夫发现。", use: "钬激光（医用碎石）、磁通聚集器、磁光存储。" },
    "Er": { disc: "1843 年由莫桑德尔发现。", use: "光纤放大器（光纤通信核心）、激光手术、玫瑰色玻璃。" },
    "Tm": { disc: "1879 年由克莱夫发现。", use: "便携式 X 射线源、激光器、金属卤化物灯。" },
    "Yb": { disc: "1878 年由马里尼亚克发现。", use: "镱原子钟（最精准时钟之一）、光纤激光器。" },
    "Lu": { disc: "1907 年由于尔班发现。", use: "PET 扫描闪烁体、石油裂化催化剂、激光材料。" },
    "Hf": { disc: "1923 年由科斯特与赫维西发现。", use: "核反应堆控制棒、芯片高介电常数栅介质、超硬碳化铪。" },
    "Ta": { disc: "1802 年由埃克贝里发现。", use: "钽电容器（手机与航天）、手术器械、化工耐蚀设备。" },
    "W": { disc: "1783 年由埃尔希亚尔兄弟发现。", use: "白炽灯丝、硬质合金刀具、穿甲弹与高密度配重。" },
    "Re": { disc: "1925 年由诺达克夫妇发现。", use: "航空发动机单晶叶片合金、石油重整催化剂。" },
    "Os": { disc: "1803 年由坦南特与武拉斯顿发现。", use: "笔尖与电触点合金、四氧化锇显微染色剂。" },
    "Ir": { disc: "1803 年由坦南特发现。", use: "火花塞电极、坩埚、铱-192 放疗源、恐龙灭绝陨石证据层。" },
    "Pt": { disc: "1735 年由乌略亚记载。", use: "汽车催化转化器、首饰、化疗药物顺铂、标准电极。" },
    "Au": { disc: "远古即知，古代货币与工艺品。", use: "首饰与储备资产、电子键合线、牙科与精密触点。" },
    "Hg": { disc: "远古即知，古代炼丹术核心原料。", use: "温度计血压计（渐淘汰）、荧光灯、氯碱工业（历史）。" },
    "Tl": { disc: "1861 年由克鲁克斯光谱发现。", use: "红外探测器、伽马闪烁体，历史上曾用作毒鼠药（已禁）。" },
    "Pb": { disc: "远古即知，古罗马大量使用铅管。", use: "铅酸电池、辐射屏蔽、配重与焊料（渐淘汰）。" },
    "Bi": { disc: "约 1753 年由若弗鲁瓦确认。", use: "胃药（次水杨酸铋）、低熔点合金、化妆品珠光颜料。" },
    "Po": { disc: "1898 年由居里夫妇发现，以波兰命名。", use: "静电消除器、微量热电核电池（历史）、科研放射源。" },
    "At": { disc: "1940 年由科尔森与塞格雷等人人工合成。", use: "仅用于科学研究，天然存量极少，无实际用途。" },
    "Rn": { disc: "1900 年由多恩发现。", use: "历史上曾用于放射治疗；环境中需防范地下室氡气积累。" },
    "Fr": { disc: "1939 年由佩雷发现，以法国命名。", use: "仅用于科学研究，半衰期极短，天然含量近乎为零。" },
    "Ra": { disc: "1898 年由居里夫妇发现。", use: "曾用于夜光涂料与早期放疗（均已弃用），现仅科研。" },
    "Ac": { disc: "1899 年由德比尔纳发现。", use: "钍基核燃料研究、中子源与靶向放疗研究。" },
    "Th": { disc: "1829 年由贝采利乌斯发现，以北欧雷神命名。", use: "钍基熔盐核电研究、历史上用于汽灯纱罩与镁合金。" },
    "Pa": { disc: "1913 年由法扬斯与格林发现。", use: "科研示踪剂，用于测定海洋沉积物与地质年代。" },
    "U": { disc: "1789 年由克拉普罗特发现，以天王星命名。", use: "核燃料、核武器、贫铀穿甲弹与配重、放射性测年。" },
    "Np": { disc: "1940 年由麦克米伦与阿贝尔森合成，以海王星命名。", use: "中子探测器、科研用途。" },
    "Pu": { disc: "1940 年由西博格团队合成，以冥王星命名。", use: "核武器、深空探测器核电池（旅行者号、好奇号）。" },
    "Am": { disc: "1944 年由西博格团队合成，以美洲命名。", use: "烟雾探测器电离室（家用最常见放射性制品）。" },
    "Cm": { disc: "1944 年由西博格团队合成，以居里夫妇命名。", use: "航天器放射性同位素热源、火星车 APXS 分析仪。" },
    "Bk": { disc: "1949 年人工合成，以伯克利命名。", use: "仅用于科研，主要作为合成更重元素的靶材。" },
    "Cf": { disc: "1950 年人工合成，以加州命名。", use: "强中子源：中子活化分析、油田测井、行李安检。" },
    "Es": { disc: "1952 年在热核试验尘埃中发现，以爱因斯坦命名。", use: "仅用于科研，产量以原子数计。" },
    "Fm": { disc: "1952 年在热核试验尘埃中发现，以费米命名。", use: "仅用于科研。" },
    "Md": { disc: "1955 年人工合成，以门捷列夫命名。", use: "仅用于科研。" },
    "No": { disc: "1958 年人工合成，以诺贝尔命名。", use: "仅用于科研。" },
    "Lr": { disc: "1961 年人工合成，以劳伦斯命名。", use: "仅用于科研。" },
    "Rf": { disc: "1964 年由杜布纳实验室合成，以卢瑟福命名。", use: "仅用于科研。" },
    "Db": { disc: "1967—1970 年间合成，以杜布纳命名。", use: "仅用于科研。" },
    "Sg": { disc: "1974 年人工合成，以西博格命名（首个以在世人物命名的元素）。", use: "仅用于科研。" },
    "Bh": { disc: "1981 年人工合成，以玻尔命名。", use: "仅用于科研。" },
    "Hs": { disc: "1984 年人工合成，以黑森州命名。", use: "仅用于科研。" },
    "Mt": { disc: "1982 年人工合成，以迈特纳命名。", use: "仅用于科研。" },
    "Ds": { disc: "1994 年人工合成，以达姆施塔特命名。", use: "仅用于科研。" },
    "Rg": { disc: "1994 年人工合成，以伦琴命名。", use: "仅用于科研。" },
    "Cn": { disc: "1996 年人工合成，以哥白尼命名。", use: "仅用于科研。" },
    "Nh": { disc: "2004 年由日本理化学研究所合成，为首个亚洲命名的元素。", use: "仅用于科研。" },
    "Fl": { disc: "1999 年由杜布纳实验室合成。", use: "仅用于科研。" },
    "Mc": { disc: "2003 年由杜布纳实验室合成，以弗廖罗夫命名。", use: "仅用于科研。" },
    "Lv": { disc: "2000 年由杜布纳实验室合成，以利弗莫尔实验室命名。", use: "仅用于科研。" },
    "Ts": { disc: "2010 年由杜布纳实验室合成，以田纳西州命名。", use: "仅用于科研。" },
    "Og": { disc: "2002 年由杜布纳实验室首次合成，以奥加尼扬命名。", use: "仅用于科研，迄今仅合成数个原子。" },
  };

  /* 数据更新时间：修订任何数据表（新增元素 / 修正原子质量 / 物性数据等）时同步更新此日期，页面图例底部会展示 */
  var DATA_UPDATED = "2026-09-16";

  /* ---------------- ELEMENT_PHYS：物理性质（熔点 / 沸点 / 密度） ---------------- */
  // 熔点 / 沸点单位 ℃；密度单位 g/cm³，常温气态元素用 g/L（20.9 条已标注）；
  // 带"（估算）"的为理论或外推值；"—"为尚无可靠实验数据。
  // 超重元素（104 号起 Rf~Og）半衰期极短，物理性质基本只有理论预测，统一记 "—"。
  var ELEMENT_PHYS = {
    "H": { mp: "-259.2", bp: "-252.9", den: "0.0899 g/L" },
    "He": { mp: "-272.2（高压下）", bp: "-268.9", den: "0.1785 g/L" },
    "Li": { mp: "180.5", bp: "1342", den: "0.534" },
    "Be": { mp: "1287", bp: "2469", den: "1.85" },
    "B": { mp: "2076", bp: "3927", den: "2.34" },
    "C": { mp: "≈3550", bp: "≈4027（常压升华）", den: "2.26（石墨）" },
    "N": { mp: "-210.0", bp: "-195.8", den: "1.251 g/L" },
    "O": { mp: "-218.8", bp: "-183.0", den: "1.429 g/L" },
    "F": { mp: "-219.7", bp: "-188.1", den: "1.696 g/L" },
    "Ne": { mp: "-248.6", bp: "-246.1", den: "0.900 g/L" },
    "Na": { mp: "97.8", bp: "883", den: "0.971" },
    "Mg": { mp: "650", bp: "1090", den: "1.738" },
    "Al": { mp: "660.3", bp: "2470", den: "2.70" },
    "Si": { mp: "1414", bp: "3265", den: "2.33" },
    "P": { mp: "44.2（白磷）", bp: "280.5（白磷）", den: "1.82（白磷）" },
    "S": { mp: "115.2", bp: "444.6", den: "2.07" },
    "Cl": { mp: "-101.5", bp: "-34.0", den: "3.21 g/L" },
    "Ar": { mp: "-189.3", bp: "-185.8", den: "1.784 g/L" },
    "K": { mp: "63.5", bp: "759", den: "0.862" },
    "Ca": { mp: "842", bp: "1484", den: "1.55" },
    "Sc": { mp: "1541", bp: "2836", den: "2.99" },
    "Ti": { mp: "1668", bp: "3287", den: "4.51" },
    "V": { mp: "1910", bp: "3407", den: "6.0" },
    "Cr": { mp: "1907", bp: "2671", den: "7.15" },
    "Mn": { mp: "1246", bp: "2061", den: "7.3" },
    "Fe": { mp: "1538", bp: "2861", den: "7.87" },
    "Co": { mp: "1495", bp: "2927", den: "8.86" },
    "Ni": { mp: "1455", bp: "2913", den: "8.91" },
    "Cu": { mp: "1084.6", bp: "2562", den: "8.96" },
    "Zn": { mp: "419.5", bp: "907", den: "7.14" },
    "Ga": { mp: "29.8", bp: "2204", den: "5.91" },
    "Ge": { mp: "938.2", bp: "2833", den: "5.32" },
    "As": { mp: "817（高压下）", bp: "615（升华）", den: "5.75" },
    "Se": { mp: "221", bp: "685", den: "4.81" },
    "Br": { mp: "-7.2", bp: "58.8", den: "3.12（液态）" },
    "Kr": { mp: "-157.4", bp: "-153.2", den: "3.75 g/L" },
    "Rb": { mp: "39.3", bp: "688", den: "1.53" },
    "Sr": { mp: "777", bp: "1382", den: "2.64" },
    "Y": { mp: "1526", bp: "3336", den: "4.47" },
    "Zr": { mp: "1855", bp: "4409", den: "6.52" },
    "Nb": { mp: "2477", bp: "4744", den: "8.57" },
    "Mo": { mp: "2623", bp: "4639", den: "10.2" },
    "Tc": { mp: "2157", bp: "4265", den: "11.5（估算）" },
    "Ru": { mp: "2334", bp: "4150", den: "12.4" },
    "Rh": { mp: "1964", bp: "3695", den: "12.4" },
    "Pd": { mp: "1554.9", bp: "2963", den: "12.0" },
    "Ag": { mp: "961.8", bp: "2162", den: "10.5" },
    "Cd": { mp: "321.1", bp: "767", den: "8.69" },
    "In": { mp: "156.6", bp: "2072", den: "7.31" },
    "Sn": { mp: "231.9", bp: "2602", den: "7.29" },
    "Sb": { mp: "630.6", bp: "1587", den: "6.69" },
    "Te": { mp: "449.5", bp: "988", den: "6.23" },
    "I": { mp: "113.7", bp: "184.3", den: "4.93" },
    "Xe": { mp: "-111.8", bp: "-108.0", den: "5.9 g/L" },
    "Cs": { mp: "28.4", bp: "671", den: "1.93" },
    "Ba": { mp: "727", bp: "1845", den: "3.62" },
    "La": { mp: "920", bp: "3464", den: "6.16" },
    "Ce": { mp: "795", bp: "3443", den: "6.77" },
    "Pr": { mp: "935", bp: "3520", den: "6.77" },
    "Nd": { mp: "1024", bp: "3074", den: "7.01" },
    "Pm": { mp: "1042", bp: "≈3000（估算）", den: "7.26（估算）" },
    "Sm": { mp: "1072", bp: "1794", den: "7.52" },
    "Eu": { mp: "822", bp: "1529", den: "5.24" },
    "Gd": { mp: "1312", bp: "3273", den: "7.90" },
    "Tb": { mp: "1356", bp: "3230", den: "8.23" },
    "Dy": { mp: "1412", bp: "2567", den: "8.55" },
    "Ho": { mp: "1474", bp: "2700", den: "8.80" },
    "Er": { mp: "1529", bp: "2868", den: "9.07" },
    "Tm": { mp: "1545", bp: "1950", den: "9.32" },
    "Yb": { mp: "824", bp: "1196", den: "6.90" },
    "Lu": { mp: "1663", bp: "3402", den: "9.84" },
    "Hf": { mp: "2233", bp: "4603", den: "13.3" },
    "Ta": { mp: "3017", bp: "5458", den: "16.7" },
    "W": { mp: "3422", bp: "5555", den: "19.3" },
    "Re": { mp: "3186", bp: "5596", den: "21.0" },
    "Os": { mp: "3033", bp: "5012", den: "22.6（密度最大元素）" },
    "Ir": { mp: "2446", bp: "4428", den: "22.5" },
    "Pt": { mp: "1768.3", bp: "3825", den: "21.5" },
    "Au": { mp: "1064.2", bp: "2856", den: "19.3" },
    "Hg": { mp: "-38.8", bp: "356.7", den: "13.5（液态）" },
    "Tl": { mp: "304", bp: "1473", den: "11.9" },
    "Pb": { mp: "327.5", bp: "1749", den: "11.3" },
    "Bi": { mp: "271.4", bp: "1564", den: "9.79" },
    "Po": { mp: "254", bp: "962", den: "9.20" },
    "At": { mp: "302（估算）", bp: "337（估算）", den: "—" },
    "Rn": { mp: "-71.0", bp: "-61.7", den: "9.73 g/L" },
    "Fr": { mp: "27（估算）", bp: "677（估算）", den: "—" },
    "Ra": { mp: "700", bp: "1737", den: "5.5" },
    "Ac": { mp: "1050", bp: "≈3200（估算）", den: "10.1（估算）" },
    "Th": { mp: "1750", bp: "4788", den: "11.7" },
    "Pa": { mp: "1572", bp: "≈4000（估算）", den: "15.4" },
    "U": { mp: "1135", bp: "4131", den: "19.1" },
    "Np": { mp: "644", bp: "≈3902（估算）", den: "20.5" },
    "Pu": { mp: "640", bp: "3228", den: "19.8" },
    "Am": { mp: "1176", bp: "≈2011（估算）", den: "13.7" },
    "Cm": { mp: "1345", bp: "3110", den: "13.5" },
    "Bk": { mp: "1050", bp: "—", den: "14.8（估算）" },
    "Cf": { mp: "900", bp: "—", den: "15.1（估算）" },
    "Es": { mp: "860", bp: "—", den: "8.84（估算）" },
    "Fm": { mp: "1527（估算）", bp: "—", den: "—" },
    "Md": { mp: "827（估算）", bp: "—", den: "—" },
    "No": { mp: "827（估算）", bp: "—", den: "—" },
    "Lr": { mp: "1627（估算）", bp: "—", den: "—" },
    "Rf": { mp: "—", bp: "—", den: "—" },
    "Db": { mp: "—", bp: "—", den: "—" },
    "Sg": { mp: "—", bp: "—", den: "—" },
    "Bh": { mp: "—", bp: "—", den: "—" },
    "Hs": { mp: "—", bp: "—", den: "—" },
    "Mt": { mp: "—", bp: "—", den: "—" },
    "Ds": { mp: "—", bp: "—", den: "—" },
    "Rg": { mp: "—", bp: "—", den: "—" },
    "Cn": { mp: "—", bp: "—", den: "—" },
    "Nh": { mp: "—", bp: "—", den: "—" },
    "Fl": { mp: "—", bp: "—", den: "—" },
    "Mc": { mp: "—", bp: "—", den: "—" },
    "Lv": { mp: "—", bp: "—", den: "—" },
    "Ts": { mp: "—", bp: "—", den: "—" },
    "Og": { mp: "—", bp: "—", den: "—" },
  };

  /* 启动自检：每张数据表都必须按 sym 与 ELEMENTS 精确一一对应。
     结果写入全局 ELEMENT_DATA_OK：失败时在页面上给出明确诊断，并让 main.js 拒绝启动——
     本文件是独立 <script>，直接抛错无法中止 main.js，只会在 main.js 深处引发误导性报错 */
  window.ELEMENT_DATA_OK = (function () {
    var tables = { ELEMENT_EXTRAS: ELEMENT_EXTRAS, ELEMENT_MORE: ELEMENT_MORE, ELEMENT_PHYS: ELEMENT_PHYS };
    try {
      for (var tableName in tables) {
        if (!Object.prototype.hasOwnProperty.call(tables, tableName)) continue;
        var table = tables[tableName];
        var seen = {};
        var keys = Object.keys(table);
        for (var i = 0; i < keys.length; i++) seen[keys[i]] = true;
        for (var j = 0; j < ELEMENTS.length; j++) {
          var s = ELEMENTS[j].sym;
          if (!seen[s]) {
            throw new Error(tableName + " 缺少元素 " + s + " 的数据（须按符号一一对应）");
          }
          delete seen[s];
        }
        for (var k in seen) {
          if (Object.prototype.hasOwnProperty.call(seen, k)) {
            throw new Error(tableName + " 存在未知符号 " + k + "（必须与 ELEMENTS.sym 精确匹配）");
          }
        }
      }
      return true;
    } catch (e) {
      var msg = "元素数据自检失败：" + (e && e.message ? e.message : e);
      if (window.console && console.error) console.error("[element-data] " + msg);
      var tip = document.createElement("div");
      tip.style.cssText =
        "position:fixed;inset:0;z-index:99;display:flex;align-items:center;justify-content:center;" +
        "background:#0d1b2a;color:#ff8080;font:14px/1.8 monospace;padding:24px;text-align:center;";
      tip.textContent = msg;
      document.body.appendChild(tip);
      return false;
    }
  })();
